import type { Depot } from "@/@types/depot";
export const mockDepots: Depot[] = [
  {
    id: 1,
    name: "Depot HCM - Quận 1",
    mapId: "HCM001",
    province: "TP. Hồ Chí Minh",
    district: "Quận 1",
    ward: "Phường Bến Nghé",
    street: "22 Lê Lợi",
  },
  {
    id: 2,
    name: "Depot HCM - Quận 3",
    mapId: "HCM002",
    province: "TP. Hồ Chí Minh",
    district: "Quận 3",
    ward: "Phường 7",
    street: "120 Cách Mạng Tháng 8",
  },
  {
    id: 3,
    name: "Depot HCM - Thủ Đức",
    mapId: "HCM003",
    province: "TP. Hồ Chí Minh",
    district: "TP Thủ Đức",
    ward: "Phường Linh Trung",
    street: "45 Võ Văn Ngân",
  },

  // Hà Nội
  {
    id: 4,
    name: "Depot HN - Hoàn Kiếm",
    mapId: "HN001",
    province: "Hà Nội",
    district: "Hoàn Kiếm",
    ward: "Phường Hàng Bài",
    street: "10 Tràng Tiền",
  },
  {
    id: 5,
    name: "Depot HN - Cầu Giấy",
    mapId: "HN002",
    province: "Hà Nội",
    district: "Cầu Giấy",
    ward: "Phường Dịch Vọng",
    street: "85 Cầu Giấy",
  },
  {
    id: 6,
    name: "Depot HN - Thanh Xuân",
    mapId: "HN003",
    province: "Hà Nội",
    district: "Thanh Xuân",
    ward: "Phường Khương Trung",
    street: "60 Nguyễn Trãi",
  },

  // Đà Nẵng
  {
    id: 7,
    name: "Depot ĐN - Hải Châu",
    mapId: "DN001",
    province: "Đà Nẵng",
    district: "Hải Châu",
    ward: "Phường Thạch Thang",
    street: "15 Bạch Đằng",
  },
  {
    id: 8,
    name: "Depot ĐN - Thanh Khê",
    mapId: "DN002",
    province: "Đà Nẵng",
    district: "Thanh Khê",
    ward: "Phường Vĩnh Trung",
    street: "75 Điện Biên Phủ",
  },
  {
    id: 9,
    name: "Depot ĐN - Sơn Trà",
    mapId: "DN003",
    province: "Đà Nẵng",
    district: "Sơn Trà",
    ward: "Phường An Hải Bắc",
    street: "25 Phạm Văn Đồng",
  },

  // Cần Thơ
  {
    id: 10,
    name: "Depot CT - Ninh Kiều",
    mapId: "CT001",
    province: "Cần Thơ",
    district: "Ninh Kiều",
    ward: "Phường An Phú",
    street: "90 Nguyễn Trãi",
  },
  {
    id: 11,
    name: "Depot CT - Bình Thủy",
    mapId: "CT002",
    province: "Cần Thơ",
    district: "Bình Thủy",
    ward: "Phường Trà Nóc",
    street: "22 Lê Hồng Phong",
  },
  {
    id: 12,
    name: "Depot CT - Cái Răng",
    mapId: "CT003",
    province: "Cần Thơ",
    district: "Cái Răng",
    ward: "Phường Hưng Phú",
    street: "180 Võ Nguyên Giáp",
  },
];
