import type { Car } from "@/@types/car";
import mazda3 from "@/images/mazda3.png";

export const mockCars: Car[] = [
  {
    id: "vf3",
    name: "VinFast VF3",
    image: mazda3,
    model: "Vinfast",
    pricePerDay: 590000,
    seats: 4,
    rating: 4.8,
    trips: 120,
    freeDeposit: true,
    discount: 10,
    province: "TP. Hồ Chí Minh",
    rangeKm: 220,
    horsepower: 43,
    trunkLiters: 285,
    bodyType: "Mini",
    dailyKmLimit: 300,
    amenities: ["Màn hình 7 inch", "La-zăng 15 inch"],
  },
  {
    id: "fadil-2020",
    name: "VinFast Fadil 2020",
    image: mazda3,
    model: "Vinfast",
    pricePerDay: 520000,
    seats: 4,
    rating: 4.6,
    trips: 200,
    freeDeposit: true,
    discount: 0,
    province: "Hà Nội",
    rangeKm: 240,
    horsepower: 98,
    trunkLiters: 280,
    bodyType: "Hatchback",
    dailyKmLimit: 300,
    amenities: ["Bluetooth", "Cảm biến lùi"],
  },
  {
    id: "lux-a2-2019",
    name: "VinFast Lux A2.0 2019",
    image: mazda3,
    model: "Vinfast",
    pricePerDay: 850000,
    seats: 5,
    rating: 4.7,
    trips: 90,
    freeDeposit: false,
    discount: 15,
    province: "Đà Nẵng",
    rangeKm: 280,
    horsepower: 174,
    trunkLiters: 500,
    bodyType: "Sedan",
    dailyKmLimit: 320,
    amenities: ["Cruise Control", "Apple CarPlay"],
  },
  {
    id: "honda-city-2020",
    name: "Honda City 2020",
    image: mazda3,
    model: "Honda",
    pricePerDay: 600000,
    seats: 5,
    rating: 4.5,
    trips: 180,
    freeDeposit: true,
    discount: 0,
    province: "Cần Thơ",
    rangeKm: 270,
    horsepower: 119,
    trunkLiters: 506,
    bodyType: "Sedan",
    dailyKmLimit: 300,
    amenities: ["Camera lùi", "Điều hòa tự động"],
  },
  {
    id: "honda-civic-2021",
    name: "Honda Civic 2021",
    image: mazda3,
    model: "Honda",
    pricePerDay: 780000,
    seats: 5,
    rating: 4.8,
    trips: 220,
    freeDeposit: true,
    discount: 10,
    province: "TP. Hồ Chí Minh",
    rangeKm: 290,
    horsepower: 176,
    trunkLiters: 430,
    bodyType: "Sedan",
    dailyKmLimit: 320,
    amenities: ["Hỗ trợ phanh ABS", "Apple CarPlay"],
  },
  {
    id: "honda-crv-2019",
    name: "Honda CR-V 2019",
    image: mazda3,
    model: "Honda",
    pricePerDay: 950000,
    seats: 7,
    rating: 4.7,
    trips: 130,
    freeDeposit: false,
    discount: 5,
    province: "Hà Nội",
    rangeKm: 360,
    horsepower: 188,
    trunkLiters: 589,
    bodyType: "SUV",
    dailyKmLimit: 350,
    amenities: ["Cửa sổ trời", "Camera 360°"],
  },
  {
    id: "toyota-corolla-2020",
    name: "Toyota Corolla 2020",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 650000,
    seats: 5,
    rating: 4.6,
    trips: 80,
    freeDeposit: false,
    discount: 0,
    province: "Đà Nẵng",
    rangeKm: 260,
    horsepower: 138,
    trunkLiters: 470,
    bodyType: "Sedan",
    dailyKmLimit: 300,
    amenities: ["Màn hình giải trí 9 inch", "Bluetooth"],
  },
  {
    id: "toyota-camry-2022",
    name: "Toyota Camry 2022",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 1200000,
    seats: 5,
    rating: 4.9,
    trips: 150,
    freeDeposit: true,
    discount: 5,
    province: "Cần Thơ",
    rangeKm: 300,
    horsepower: 203,
    trunkLiters: 524,
    bodyType: "Sedan",
    dailyKmLimit: 350,
    amenities: ["Điều hòa 2 vùng", "Ghế da chỉnh điện"],
  },
  {
    id: "toyota-vios-2019",
    name: "Toyota Vios 2019",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 550000,
    seats: 5,
    rating: 4.4,
    trips: 300,
    freeDeposit: true,
    discount: 0,
    province: "TP. Hồ Chí Minh",
    rangeKm: 270,
    horsepower: 107,
    trunkLiters: 476,
    bodyType: "Sedan",
    dailyKmLimit: 300,
    amenities: ["Camera lùi", "Bluetooth"],
  },
  {
    id: "toyota-fortuner-2021",
    name: "Toyota Fortuner 2021",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 1350000,
    seats: 7,
    rating: 4.7,
    trips: 110,
    freeDeposit: false,
    discount: 12,
    province: "Hà Nội",
    rangeKm: 380,
    horsepower: 201,
    trunkLiters: 489,
    bodyType: "SUV",
    dailyKmLimit: 350,
    amenities: ["Cảm biến lùi", "Camera 360°"],
  },
  {
    id: "hyundai-kona-2021",
    name: "Hyundai Kona 2021",
    image: mazda3,
    model: "Hyundai",
    pricePerDay: 707000,
    seats: 5,
    rating: 4.9,
    trips: 210,
    freeDeposit: true,
    discount: 20,
    province: "Đà Nẵng",
    rangeKm: 280,
    horsepower: 147,
    trunkLiters: 361,
    bodyType: "CUV",
    dailyKmLimit: 320,
    amenities: ["Màn hình cảm ứng", "Apple CarPlay"],
  },
  {
    id: "hyundai-accent-2021",
    name: "Hyundai Accent 2021",
    image: mazda3,
    model: "Hyundai",
    pricePerDay: 560000,
    seats: 5,
    rating: 4.5,
    trips: 170,
    freeDeposit: false,
    discount: 12,
    province: "Cần Thơ",
    rangeKm: 290,
    horsepower: 100,
    trunkLiters: 387,
    bodyType: "Sedan",
    dailyKmLimit: 300,
    amenities: ["Điều hòa tự động", "Bluetooth"],
  },
  {
    id: "hyundai-santafe-2020",
    name: "Hyundai SantaFe 2020",
    image: mazda3,
    model: "Hyundai",
    pricePerDay: 1100000,
    seats: 7,
    rating: 4.8,
    trips: 140,
    freeDeposit: true,
    discount: 0,
    province: "TP. Hồ Chí Minh",
    rangeKm: 350,
    horsepower: 202,
    trunkLiters: 634,
    bodyType: "SUV",
    dailyKmLimit: 350,
    amenities: ["Ghế sưởi", "Cửa sổ trời"],
  },
  {
    id: "kia-cerato-2019",
    name: "Kia Cerato 2019",
    image: mazda3,
    model: "Kia",
    pricePerDay: 580000,
    seats: 5,
    rating: 4.5,
    trips: 140,
    freeDeposit: true,
    discount: 15,
    province: "Hà Nội",
    rangeKm: 270,
    horsepower: 128,
    trunkLiters: 502,
    bodyType: "Sedan",
    dailyKmLimit: 300,
    amenities: ["Cruise Control", "Bluetooth"],
  },
  {
    id: "kia-morning-2020",
    name: "Kia Morning 2020",
    image: mazda3,
    model: "Kia",
    pricePerDay: 450000,
    seats: 4,
    rating: 4.4,
    trips: 300,
    freeDeposit: true,
    discount: 0,
    province: "Đà Nẵng",
    rangeKm: 230,
    horsepower: 83,
    trunkLiters: 255,
    bodyType: "Hatchback",
    dailyKmLimit: 300,
    amenities: ["Màn hình 8 inch", "Bluetooth"],
  },
  {
    id: "kia-seltos-2021",
    name: "Kia Seltos 2021",
    image: mazda3,
    model: "Kia",
    pricePerDay: 720000,
    seats: 5,
    rating: 4.6,
    trips: 160,
    freeDeposit: false,
    discount: 10,
    province: "Cần Thơ",
    rangeKm: 280,
    horsepower: 138,
    trunkLiters: 433,
    bodyType: "CUV",
    dailyKmLimit: 320,
    amenities: ["Apple CarPlay", "Điều hòa 2 vùng"],
  },
  {
    id: "chevrolet-cruze-2019",
    name: "Chevrolet Cruze 2019",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 580000,
    seats: 5,
    rating: 4.3,
    trips: 120,
    freeDeposit: true,
    discount: 0,
    province: "TP. Hồ Chí Minh",
    rangeKm: 260,
    horsepower: 153,
    trunkLiters: 419,
    bodyType: "Sedan",
    dailyKmLimit: 300,
    amenities: ["Màn hình cảm ứng", "Bluetooth"],
  },
  {
    id: "chevrolet-trax-2018",
    name: "Chevrolet Trax 2018",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 620000,
    seats: 5,
    rating: 4.2,
    trips: 90,
    freeDeposit: false,
    discount: 8,
    province: "Hà Nội",
    rangeKm: 290,
    horsepower: 138,
    trunkLiters: 356,
    bodyType: "CUV",
    dailyKmLimit: 300,
    amenities: ["Cruise Control", "Camera lùi"],
  },
  {
    id: "chevrolet-colorado-2020",
    name: "Chevrolet Colorado 2020",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 950000,
    seats: 5,
    rating: 4.6,
    trips: 100,
    freeDeposit: true,
    discount: 0,
    province: "Đà Nẵng",
    rangeKm: 280,
    horsepower: 200,
    trunkLiters: 470,
    bodyType: "Pickup",
    dailyKmLimit: 350,
    amenities: ["Hỗ trợ đổ đèo", "Cảm biến lùi"],
  },
  {
    id: "chevrolet-captiva-2019",
    name: "Chevrolet Captiva 2019",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 880000,
    seats: 7,
    rating: 4.5,
    trips: 130,
    freeDeposit: true,
    discount: 12,
    province: "Cần Thơ",
    rangeKm: 370,
    horsepower: 180,
    trunkLiters: 477,
    bodyType: "SUV",
    dailyKmLimit: 350,
    amenities: ["Cửa sổ trời", "Camera lùi"],
  },
];
