import type { Car } from "@/@types/car";
import mazda3 from "@/images/mazda3.png";

export const mockCars: Car[] = [
  {
    id: "vf3",
    name: "VinFast VF3",
    image: mazda3,
    model: "Vinfast", // 👈 model là brand
    pricePerDay: 590000,
    seats: 4,
    rating: 4.8,
    trips: 120,
    freeDeposit: true,
    discount: 10,
    province: "TP. Hồ Chí Minh",
  },
  {
    id: "fadil-2020",
    name: "VinFast Fadil 2020",
    image: mazda3,
    model: "Vinfast",
    pricePerDay: 520000,
    seats: 4,
    rating: 4.6,
    trips: 200,
    freeDeposit: true,
    discount: 0,
    province: "Hà Nội",
  },
  {
    id: "lux-a2-2019",
    name: "VinFast Lux A2.0 2019",
    image: mazda3,
    model: "Vinfast",
    pricePerDay: 850000,
    seats: 5,
    rating: 4.7,
    trips: 90,
    freeDeposit: false,
    discount: 15,
    province: "Đà Nẵng",
  },
  {
    id: "honda-city-2020",
    name: "Honda City 2020",
    image: mazda3,
    model: "Honda",
    pricePerDay: 600000,
    seats: 5,
    rating: 4.5,
    trips: 180,
    freeDeposit: true,
    discount: 0,
    province: "Cần Thơ",
  },
  {
    id: "honda-civic-2021",
    name: "Honda Civic 2021",
    image: mazda3,
    model: "Honda",
    pricePerDay: 780000,
    seats: 5,
    rating: 4.8,
    trips: 220,
    freeDeposit: true,
    discount: 10,
    province: "TP. Hồ Chí Minh",
  },
  {
    id: "honda-crv-2019",
    name: "Honda CR-V 2019",
    image: mazda3,
    model: "Honda",
    pricePerDay: 950000,
    seats: 7,
    rating: 4.7,
    trips: 130,
    freeDeposit: false,
    discount: 5,
    province: "Hà Nội",
  },
  {
    id: "toyota-corolla-2020",
    name: "Toyota Corolla 2020",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 650000,
    seats: 5,
    rating: 4.6,
    trips: 80,
    freeDeposit: false,
    discount: 0,
    province: "Đà Nẵng",
  },
  {
    id: "toyota-camry-2022",
    name: "Toyota Camry 2022",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 1200000,
    seats: 5,
    rating: 4.9,
    trips: 150,
    freeDeposit: true,
    discount: 5,
    province: "Cần Thơ",
  },
  {
    id: "toyota-vios-2019",
    name: "Toyota Vios 2019",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 550000,
    seats: 5,
    rating: 4.4,
    trips: 300,
    freeDeposit: true,
    discount: 0,
    province: "TP. Hồ Chí Minh",
  },
  {
    id: "toyota-fortuner-2021",
    name: "Toyota Fortuner 2021",
    image: mazda3,
    model: "Toyota",
    pricePerDay: 1350000,
    seats: 7,
    rating: 4.7,
    trips: 110,
    freeDeposit: false,
    discount: 12,
    province: "Hà Nội",
  },
  {
    id: "hyundai-kona-2021",
    name: "Hyundai Kona 2021",
    image: mazda3,
    model: "Hyundai",
    pricePerDay: 707000,
    seats: 5,
    rating: 4.9,
    trips: 210,
    freeDeposit: true,
    discount: 20,
    province: "Đà Nẵng",
  },
  {
    id: "hyundai-accent-2021",
    name: "Hyundai Accent 2021",
    image: mazda3,
    model: "Hyundai",
    pricePerDay: 560000,
    seats: 5,
    rating: 4.5,
    trips: 170,
    freeDeposit: false,
    discount: 12,
    province: "Cần Thơ",
  },
  {
    id: "hyundai-santafe-2020",
    name: "Hyundai SantaFe 2020",
    image: mazda3,
    model: "Hyundai",
    pricePerDay: 1100000,
    seats: 7,
    rating: 4.8,
    trips: 140,
    freeDeposit: true,
    discount: 0,
    province: "TP. Hồ Chí Minh",
  },
  {
    id: "kia-cerato-2019",
    name: "Kia Cerato 2019",
    image: mazda3,
    model: "Kia",
    pricePerDay: 580000,
    seats: 5,
    rating: 4.5,
    trips: 140,
    freeDeposit: true,
    discount: 15,
    province: "Hà Nội",
  },
  {
    id: "kia-morning-2020",
    name: "Kia Morning 2020",
    image: mazda3,
    model: "Kia",
    pricePerDay: 450000,
    seats: 4,
    rating: 4.4,
    trips: 300,
    freeDeposit: true,
    discount: 0,
    province: "Đà Nẵng",
  },
  {
    id: "kia-seltos-2021",
    name: "Kia Seltos 2021",
    image: mazda3,
    model: "Kia",
    pricePerDay: 720000,
    seats: 5,
    rating: 4.6,
    trips: 160,
    freeDeposit: false,
    discount: 10,
    province: "Cần Thơ",
  },
  {
    id: "chevrolet-cruze-2019",
    name: "Chevrolet Cruze 2019",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 580000,
    seats: 5,
    rating: 4.3,
    trips: 120,
    freeDeposit: true,
    discount: 0,
    province: "TP. Hồ Chí Minh",
  },
  {
    id: "chevrolet-trax-2018",
    name: "Chevrolet Trax 2018",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 620000,
    seats: 5,
    rating: 4.2,
    trips: 90,
    freeDeposit: false,
    discount: 8,
    province: "Hà Nội",
  },
  {
    id: "chevrolet-colorado-2020",
    name: "Chevrolet Colorado 2020",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 950000,
    seats: 5,
    rating: 4.6,
    trips: 100,
    freeDeposit: true,
    discount: 0,
    province: "Đà Nẵng",
  },
  {
    id: "chevrolet-captiva-2019",
    name: "Chevrolet Captiva 2019",
    image: mazda3,
    model: "Chevrolet",
    pricePerDay: 880000,
    seats: 7,
    rating: 4.5,
    trips: 130,
    freeDeposit: true,
    discount: 12,
    province: "Cần Thơ",
  },
];
