export type Contract = {
  orderId: string;
  title: string;
  contractNumber: string;
  contractDate: string;
  lessorId: string;
  lessorCompanyName: string;
  lessorAddress: string;
  lessorPhone?: string;
  lessorEmail?: string;
  lesseeFullName: string;
  lesseeIdNumber: string;
  lesseePhone: string;
  lesseeAddress: string;
  lesseeDateOfBirth: string;
  lesseeEmail?: string;
  vehicleCode: string;
  gplx: string;
  cccd: string;
  licensePlates: string;
  rentalDays: number;
  rentalStartDate: string;
  rentalEndDate: string;
  pickupAddress: string;
  dailyRate: number;
  vatRate: number;
  overMileageFee: string;
  carWashFee: string;
  depositAmount: number;
  totalPayment: number;
  remainingAmount: number;
  status: "completed" | "cancelled" | "confirmed";
  createdAt: string;
  updatedAt: string;
};
