export type Contract = {
  orderId: string;
  title: string;
  contractNumber: string;
  contractDate: string;
  lessorCompanyName: string;
  lessorAddress: string;
  lessorTaxId: string;
  lessorPhone?: string;
  lessorEmail?: string;
  lesseeFullName: string;
  lesseeIdNumber: string;
  lesseePhone: string;
  lesseeAddress: string;
  lesseeDateOfBirth: string;
  lesseeGender: "Nam" | "Nữ";
  lesseeEmail?: string;
  vehicleCode: string;
  licensePlate: string;
  rentalDurationDays: number;
  rentalStartDate: string;
  rentalEndDate: string;
  pickupAddress: string;
  dailyRate: number;
  vatRate: number;
  overMileageFee: string;
  carWashFee: string;
  depositAmount: number;
  totalPayment: number;
  status: "in_progress" | "completed" | "cancelled" | "confirmed";
  createdAt: string;
  updatedAt: string;
};
